exports.IPC_NAME = 'ipcSdk:postMessage';
exports.MAIN_IPC_NAME = 'MAIN_IPC_NAME';// 主进程通信
exports.REQUEST_REPONSE = 'RESQUEST/RESPONSE';
exports.PUBLISHER = 'PUBLISHER';
exports.SUBSCRIBER = 'SUBSCRIBER';
exports.UNSUBSCRIBER = 'UNSUBSCRIBER';
exports.PUBLISHER_SUBSCRIBER = 'PUBLISHER/SUBSCRIBER';
exports.RESPONSE_OK = 0; // 找不到服务响应注册
exports.SERVICE_NOT_FOUND = 1; // 找不到服务
exports.RESPONSE_NOT_FOUND = 2; // 找不到服务响应注册
exports.RESPONSE_OVERTIME = 3; // 响应超时