export const WINDOW_CENTER_IPC_NAME = 'ELECTRON_SUGAR:WINDOW_CENTERIPC_NAME';// 主进程通信
export const WINDOW_CENTER_REGISTER = 'ELECTRON_SUGAR:WINDOW_CENTER_REGISTER';
export const WINDOW_CENTER_UNREGISTER = 'ELECTRON_SUGAR:WINDOW_CENTER_UNREGISTER';






